### ISSUE TITLE
【parting新服务迁移】创建群聊封面图片上传会卡住

### ISSUE THREAD

**Issue by yangshuo-ola** [olachat/veeka_devtool_server#1]
uid：812695767、812732281
国内，新包#pt335
封面图片：手机自带相机拍摄
新包创建群聊，无法创建成功，群封面上传会卡住
如图所示

![Image](https://github.com/olachat/veeka_devtool_server/assets/112853119/f258ed8e-4111-4a96-bca5-dcc52587142a)

**Comment by linboyuan-ola** [comment]
传图片接口：http://api.partying.tw/upload/image
